_target_: src.modules.backbone_head_module.Backbone_Head_Module
num_classes: ${data.num_classes}

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [50000, 78000, 94000, 100000]
  gamma: 0.1

backbone:
  _target_: src.modules.components.backbone.sfnet_deprecated.sfnet20_deprecated
  in_channel: 3
  channels: [64, 128, 256, 512]
  out_channel: 512

head:
  _target_: src.modules.components.head.sphereface2.SphereFace2
  feat_dim: ${model.backbone.out_channel}
  num_class: ${data.num_classes}
  magn_type: C
  alpha: 0.7
  r: 40.0
  m: 0.4 
  t: 3.0 
  lw: 50.0

# compile model for faster training with pytorch 2.0
compile: false
